# Generated by Django 6.0.3 on 2026-03-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Hujjat turi')),
            ],
            options={
                'verbose_name': 'Hujjatlar turi - (Category)',
                'verbose_name_plural': 'Hujjatlar turi - (Category)',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Hujjat nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Narxi')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='documents/images', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('time_update', models.DateField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='documents.category', verbose_name='Hujjat turi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
