# Generated by Django 6.0.3 on 2026-03-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
