# Generated by Django 6.0.3 on 2026-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
