# Generated by Django 6.0.3 on 2026-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=190, verbose_name='Hujjat nomi'),
        ),
    ]
