# Generated by Django 6.0.3 on 2026-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='URL'),
        ),
    ]
