# Generated by Django 6.0.3 on 2026-04-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_documents_name_alter_documents_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Hujjat nomi'),
        ),
    ]
