# Generated by Django 6.0.3 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_documents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
